version: '3'

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile-nginx
        ports:
            - "80:80"
            - "81:81"
        depends_on:
            - mongo
            - app-upload
            - app-getimage
    app-upload:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        entrypoint: python ./server/server.py
        depends_on:
            - mongo
    app-getimage:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5001:5000"
        entrypoint: python ./server/get_image.py
        depends_on:
            - mongo        
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
