version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - mongo
    web-app:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
